### ISSUE TITLE
Error on server stop

### ISSUE THREAD

**Issue by Astrareach** [BananaPuncher714/Cartographer#1]
Hello, when I shutdown the server, I got an error message (happening right after the player is kicked of the server because of the shutdown) : 

Spigot version : CraftBukkit version git-Spigot-4bd94dc-015bda4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Cartographer version : "Zoom Management and Bugfixes"

Error message : https://pastebin.com/EskkXXRk
What I have done : https://pastebin.com/6Ycu7V4c

**Comment by BananaPuncher714** [comment]
Ok... This is probably the citizens module not disabling itself properly, I will fix next update. Thanks for informing me!

**Comment by BananaPuncher714** [comment]
It should be fixed now. 😃
