### ISSUE TITLE
Creative mode error

### ISSUE THREAD

**Issue by Astrareach** [BananaPuncher714/Cartographer#2]
Hello, I got an error. I just know that I was in creative mode

https://pastebin.com/CT8hpebM
Maybe related to the plugin Denizen

Regards

**Comment by BananaPuncher714** [comment]
Yes, looks like it's some denizen error. I'm not quite sure what I can do about it, but maybe the people who maintain Denizen can shed some light.

**Comment by Astrareach** [comment]
Hello, I got some possible answer : 
`You somehow have a nonsense item with invalid enchantments on it, which Spigot internals then crash on because they can't process the item.`
At this moment I had an enchanted map in one of my inventory slot (I get it from the plugin ImageOnMap) this may be the problem ?

**Comment by BananaPuncher714** [comment]
Probably ImageOnMap as Cartographer doesn't add or edit enchantments on items

**Comment by Astrareach** [comment]
Yes it is probably imageOnMap, I will see what I can do, thanks !
