### ISSUE TITLE
Error with the command /mapreload

### ISSUE THREAD

**Issue by Astrareach** [BananaPuncher714/Cartographer#4]
Greeting, the error is only in the message :
http://prntscr.com/j60t8x

Regards

**Comment by Astrareach** [comment]
& I can't zoom or dezoom anymore after reloading a map via the command & via the GUI

**Comment by BananaPuncher714** [comment]
I'll see what I can do, but using the mapreload command is deprecated and shouldn't be used. I will clean up the broken bits and add better alternatives when I have time

**Comment by BananaPuncher714** [comment]
Fixed the mapreload command to function differently!
